spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: p4ssw0rd
    url: jdbc:oracle:thin:@database-1.c7tahx74pqbv.us-east-2.rds.amazonaws.com:1521:ORCL
    username: PROJECT2_DB
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 9009